### ISSUE TITLE
mosbi installation error in network_edge_strength.cpp

### ISSUE THREAD

**Issue by cytrix1** [tdrose/mosbi#1]
I got the following error message during mosbi installation (both gihub and bioconductor install).

g++ -std=gnu++11   -I"/usr/local/lib64/R/include" -DNDEBUG  -I'/usr/local/lib64/R/library/Rcpp/include' -I'/usr/local/lib64/R/library/BH/include' -I'/usr/local/lib64/R/library/RcppParallel/include' -I/usr/local/include      -c network_edge_strength.cpp -o network_edge_strength.o
network_edge_strength.cpp: In member function ‘virtual void ReplaceWorker::operator()(std::size_t, std::size_t)’:
network_edge_strength.cpp:153:40: error: parameter declared ‘auto’
                    [this] (const auto& x) { return x < th ? 0 : 1; });
                                        ^
network_edge_strength.cpp: In lambda function:
network_edge_strength.cpp:153:52: error: ‘x’ was not declared in this scope
                    [this] (const auto& x) { return x < th ? 0 : 1; });
                                                    ^
In file included from /usr/include/c++/4.8.2/algorithm:62:0,
                 from /usr/local/lib64/R/library/RcppParallel/include/tbb/concurrent_vector.h:30,
                 from /usr/local/lib64/R/library/RcppParallel/include/tbb/enumerable_thread_specific.h:21,
                 from /usr/local/lib64/R/library/RcppParallel/include/tbb/combinable.h:20,
                 from /usr/local/lib64/R/library/RcppParallel/include/tbb/tbb.h:40,
                 from /usr/local/lib64/R/library/RcppParallel/include/RcppParallel/TBB.h:10,
                 from /usr/local/lib64/R/library/RcppParallel/include/RcppParallel.h:21,
                 from network_edge_strength.cpp:2:
/usr/include/c++/4.8.2/bits/stl_algo.h: In instantiation of ‘_OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation) [with _IIter = const double*; _OIter = double*; _UnaryOperation = ReplaceWorker::operator()(std::size_t, std::size_t)::__lambda1]’:
network_edge_strength.cpp:153:69:   required from here
/usr/include/c++/4.8.2/bits/stl_algo.h:4926:33: error: no match for call to ‘(ReplaceWorker::operator()(std::size_t, std::size_t)::__lambda1) (const double&)’
  *__result = __unary_op(*__first);
                                 ^
network_edge_strength.cpp:153:25: note: candidate is:
                    [this] (const auto& x) { return x < th ? 0 : 1; });
                         ^
network_edge_strength.cpp:153:41: note: ReplaceWorker::operator()(std::size_t, std::size_t)::__lambda1
                    [this] (const auto& x) { return x < th ? 0 : 1; });
                                         ^
network_edge_strength.cpp:153:41: note:   candidate expects 0 arguments, 1 provided
make: *** [network_edge_strength.o] Error 1
ERROR: compilation failed for package ‘mosbi’
* removing ‘/usr/local/lib64/R/library/mosbi’
Warning message:
In i.p(...) :
  installation of package ‘/tmp/Rtmp6fNfBD/file1675817580259/mosbi_1.1.10.tar.gz’ had non-zero exit status

**> sessionInfo()**
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS:   /usr/local/lib64/R/lib/libRblas.so
LAPACK: /usr/local/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] magrittr_2.0.3      usethis_2.1.6       devtools_2.4.3     
 [4] pkgload_1.2.4       R6_2.5.1            rlang_1.0.2        
 [7] fastmap_1.1.0       tcltk_4.2.0         tools_4.2.0        
[10] pkgbuild_1.3.1      sessioninfo_1.2.2   cli_3.3.0          
[13] withr_2.5.0         ellipsis_0.3.2      remotes_2.4.2      
[16] rprojroot_2.0.3     lifecycle_1.0.1     crayon_1.5.1       
[19] brio_1.1.3          processx_3.6.0      purrr_0.3.4        
[22] BiocManager_1.30.18 callr_3.7.0         fs_1.5.2           
[25] ps_1.7.0            curl_4.3.2          testthat_3.1.4     
[28] memoise_2.0.1       glue_1.6.2          cachem_1.0.6       
[31] compiler_4.2.0      desc_1.4.1          prettyunits_1.1.1

**Comment by tdrose** [comment]
Hi,
This is because you are compiling with c++11 (https://stackoverflow.com/questions/7709894/using-auto-in-a-lambda-function/7709970#7709970). mosbi requires c++17 to work.

This is listed as a requirement in the [DESCRIPTION file](https://github.com/tdrose/mosbi/blob/master/DESCRIPTION) & [Makevars](https://github.com/tdrose/mosbi/blob/master/src/Makevars), which should automatically set this as a flag for your compiler.
Please check if your compiler supports c++17 (CentOS 7 was released 2014, so it might not).

**Comment by cytrix1** [comment]
Finally installed with so many trial & errors. Basically I compiled with the anaconda-installed gcc which supports c++17.

Way around using devtoolset might be another option.

Thanks!

**Comment by LiJing-source-coder** [comment]
"library(mosbi)" cannot work, which makes the Rstudio to restart. What happened? And the path to "/library" cannot find the package "mosbi". I use BiocManager::install("mosbi") to install the package.

**Comment by tdrose** [comment]
> "library(mosbi)" cannot work, which makes the Rstudio to restart. What happened? And the path to "/library" cannot find the package "mosbi". I use BiocManager::install("mosbi") to install the package.

I need a few more information to help. What operating system and version of R are you using? Which errors are thrown by the `BiocManager::install("mosbi")` command?

**Comment by LiJing-source-coder** [comment]
Win10 and R -4.3.0;

> BiocManager::install("mosbi")

'getOption("repos")' replaces Bioconductor standard repositories, see

'help("repositories", package = "BiocManager")' for details.

Replacement repositories:

    CRAN: https://mirrors.tuna.tsinghua.edu.cn/CRAN/

Bioconductor version 3.17 (BiocManager 1.30.20), R 4.3.0 (2023-04-21 ucrt)

Installing package(s) 'mosbi'

trying URL 'https://bioconductor.org/packages/3.17/bioc/bin/windows/contrib/4.3/mosbi_1.6.0.zip'

Content type 'application/zip' length 1943354 bytes (1.9 MB)

downloaded 1.9 MB



程序包‘mosbi’打开成功，MD5和检查也通过



下载的二进制程序包在

     C:\Users\jli123\AppData\Local\Temp\RtmpoJhENG\downloaded_packages里

Installation paths not writeable, unable to update packages

  path: C:/Program Files/R/R-4.3.0/library

  packages:

class, KernSmooth, MASS, nnet


***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by tdrose** [comment]
This does not look like a mosbi specific problem. Bioconductor cannot write into your library folder due to permissions. Maybe this can help you: https://stackoverflow.com/questions/41839214/installation-path-not-writable-r-unable-to-update-packages

**Comment by LiJing-source-coder** [comment]
I installed the complier with GCC 8.1 (MinGW-w64). Specifically, refer to this website:
https://stackoverflow.com/questions/52266354/does-gcc-6-support-the-use-of-stdsample-c17

Thanks!
